import { config } from "dotenv";
import { execSync } from "node:child_process";
import { rmSync } from "node:fs";

// Vitest `globalSetup`: runs once before the whole suite. Creates a fresh
// SQLite schema in the throwaway test database so the integration tests
// have real tables to write to.
export default function setup(): void {
  // Point DATABASE_URL at the test DB for the `prisma db push` subprocess.
  config({ path: ".env.test", override: true, quiet: true });

  // Start from a pristine schema every run. prisma/test.db is gitignored
  // via "*.db"; { force: true } makes this a no-op when the file is absent.
  rmSync("prisma/test.db", { force: true });
  rmSync("prisma/test.db-journal", { force: true });

  // Create the tables. --skip-generate: the client is already generated by
  // `npm install`. --accept-data-loss: non-interactive; this DB is
  // disposable, so there is never data worth preserving.
  execSync("npx prisma db push --skip-generate --accept-data-loss", {
    stdio: "inherit",
    env: { ...process.env },
  });
}
